/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreatmentJourneysRouteImport } from './routes/treatment-journeys'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SmartPrescriptionsRouteImport } from './routes/smart-prescriptions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProceduresRouteImport } from './routes/procedures'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as PatientFollowupRouteImport } from './routes/patient-followup'
import { Route as MedicationPharmacyRouteImport } from './routes/medication-pharmacy'
import { Route as LaboratoryGameteBankRouteImport } from './routes/laboratory-gamete-bank'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as FertilityCasesRouteImport } from './routes/fertility-cases'
import { Route as DonorsRouteImport } from './routes/donors'
import { Route as ConsentsRouteImport } from './routes/consents'
import { Route as CommunicationsRouteImport } from './routes/communications'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsPatientIdRouteImport } from './routes/patients_.$patientId'
import { Route as FertilityCasesCaseIdRouteImport } from './routes/fertility-cases_.$caseId'
import { Route as InventoryLotsLotIdRouteImport } from './routes/inventory.lots.$lotId'

const TreatmentJourneysRoute = TreatmentJourneysRouteImport.update({
  id: '/treatment-journeys',
  path: '/treatment-journeys',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartPrescriptionsRoute = SmartPrescriptionsRouteImport.update({
  id: '/smart-prescriptions',
  path: '/smart-prescriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProceduresRoute = ProceduresRouteImport.update({
  id: '/procedures',
  path: '/procedures',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientFollowupRoute = PatientFollowupRouteImport.update({
  id: '/patient-followup',
  path: '/patient-followup',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationPharmacyRoute = MedicationPharmacyRouteImport.update({
  id: '/medication-pharmacy',
  path: '/medication-pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratoryGameteBankRoute = LaboratoryGameteBankRouteImport.update({
  id: '/laboratory-gamete-bank',
  path: '/laboratory-gamete-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const FertilityCasesRoute = FertilityCasesRouteImport.update({
  id: '/fertility-cases',
  path: '/fertility-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorsRoute = DonorsRouteImport.update({
  id: '/donors',
  path: '/donors',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentsRoute = ConsentsRouteImport.update({
  id: '/consents',
  path: '/consents',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationsRoute = CommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/patients_/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const FertilityCasesCaseIdRoute = FertilityCasesCaseIdRouteImport.update({
  id: '/fertility-cases_/$caseId',
  path: '/fertility-cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryLotsLotIdRoute = InventoryLotsLotIdRouteImport.update({
  id: '/lots/$lotId',
  path: '/lots/$lotId',
  getParentRoute: () => InventoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/communications': typeof CommunicationsRoute
  '/consents': typeof ConsentsRoute
  '/donors': typeof DonorsRoute
  '/fertility-cases': typeof FertilityCasesRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/laboratory-gamete-bank': typeof LaboratoryGameteBankRoute
  '/medication-pharmacy': typeof MedicationPharmacyRoute
  '/patient-followup': typeof PatientFollowupRoute
  '/patients': typeof PatientsRoute
  '/procedures': typeof ProceduresRoute
  '/settings': typeof SettingsRoute
  '/smart-prescriptions': typeof SmartPrescriptionsRoute
  '/tasks': typeof TasksRoute
  '/treatment-journeys': typeof TreatmentJourneysRoute
  '/fertility-cases/$caseId': typeof FertilityCasesCaseIdRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/inventory/lots/$lotId': typeof InventoryLotsLotIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/communications': typeof CommunicationsRoute
  '/consents': typeof ConsentsRoute
  '/donors': typeof DonorsRoute
  '/fertility-cases': typeof FertilityCasesRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/laboratory-gamete-bank': typeof LaboratoryGameteBankRoute
  '/medication-pharmacy': typeof MedicationPharmacyRoute
  '/patient-followup': typeof PatientFollowupRoute
  '/patients': typeof PatientsRoute
  '/procedures': typeof ProceduresRoute
  '/settings': typeof SettingsRoute
  '/smart-prescriptions': typeof SmartPrescriptionsRoute
  '/tasks': typeof TasksRoute
  '/treatment-journeys': typeof TreatmentJourneysRoute
  '/fertility-cases/$caseId': typeof FertilityCasesCaseIdRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/inventory/lots/$lotId': typeof InventoryLotsLotIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/communications': typeof CommunicationsRoute
  '/consents': typeof ConsentsRoute
  '/donors': typeof DonorsRoute
  '/fertility-cases': typeof FertilityCasesRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/laboratory-gamete-bank': typeof LaboratoryGameteBankRoute
  '/medication-pharmacy': typeof MedicationPharmacyRoute
  '/patient-followup': typeof PatientFollowupRoute
  '/patients': typeof PatientsRoute
  '/procedures': typeof ProceduresRoute
  '/settings': typeof SettingsRoute
  '/smart-prescriptions': typeof SmartPrescriptionsRoute
  '/tasks': typeof TasksRoute
  '/treatment-journeys': typeof TreatmentJourneysRoute
  '/fertility-cases_/$caseId': typeof FertilityCasesCaseIdRoute
  '/patients_/$patientId': typeof PatientsPatientIdRoute
  '/inventory/lots/$lotId': typeof InventoryLotsLotIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/communications'
    | '/consents'
    | '/donors'
    | '/fertility-cases'
    | '/inventory'
    | '/laboratory-gamete-bank'
    | '/medication-pharmacy'
    | '/patient-followup'
    | '/patients'
    | '/procedures'
    | '/settings'
    | '/smart-prescriptions'
    | '/tasks'
    | '/treatment-journeys'
    | '/fertility-cases/$caseId'
    | '/patients/$patientId'
    | '/inventory/lots/$lotId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/communications'
    | '/consents'
    | '/donors'
    | '/fertility-cases'
    | '/inventory'
    | '/laboratory-gamete-bank'
    | '/medication-pharmacy'
    | '/patient-followup'
    | '/patients'
    | '/procedures'
    | '/settings'
    | '/smart-prescriptions'
    | '/tasks'
    | '/treatment-journeys'
    | '/fertility-cases/$caseId'
    | '/patients/$patientId'
    | '/inventory/lots/$lotId'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analytics'
    | '/communications'
    | '/consents'
    | '/donors'
    | '/fertility-cases'
    | '/inventory'
    | '/laboratory-gamete-bank'
    | '/medication-pharmacy'
    | '/patient-followup'
    | '/patients'
    | '/procedures'
    | '/settings'
    | '/smart-prescriptions'
    | '/tasks'
    | '/treatment-journeys'
    | '/fertility-cases_/$caseId'
    | '/patients_/$patientId'
    | '/inventory/lots/$lotId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CommunicationsRoute: typeof CommunicationsRoute
  ConsentsRoute: typeof ConsentsRoute
  DonorsRoute: typeof DonorsRoute
  FertilityCasesRoute: typeof FertilityCasesRoute
  InventoryRoute: typeof InventoryRouteWithChildren
  LaboratoryGameteBankRoute: typeof LaboratoryGameteBankRoute
  MedicationPharmacyRoute: typeof MedicationPharmacyRoute
  PatientFollowupRoute: typeof PatientFollowupRoute
  PatientsRoute: typeof PatientsRoute
  ProceduresRoute: typeof ProceduresRoute
  SettingsRoute: typeof SettingsRoute
  SmartPrescriptionsRoute: typeof SmartPrescriptionsRoute
  TasksRoute: typeof TasksRoute
  TreatmentJourneysRoute: typeof TreatmentJourneysRoute
  FertilityCasesCaseIdRoute: typeof FertilityCasesCaseIdRoute
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treatment-journeys': {
      id: '/treatment-journeys'
      path: '/treatment-journeys'
      fullPath: '/treatment-journeys'
      preLoaderRoute: typeof TreatmentJourneysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-prescriptions': {
      id: '/smart-prescriptions'
      path: '/smart-prescriptions'
      fullPath: '/smart-prescriptions'
      preLoaderRoute: typeof SmartPrescriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedures': {
      id: '/procedures'
      path: '/procedures'
      fullPath: '/procedures'
      preLoaderRoute: typeof ProceduresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-followup': {
      id: '/patient-followup'
      path: '/patient-followup'
      fullPath: '/patient-followup'
      preLoaderRoute: typeof PatientFollowupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medication-pharmacy': {
      id: '/medication-pharmacy'
      path: '/medication-pharmacy'
      fullPath: '/medication-pharmacy'
      preLoaderRoute: typeof MedicationPharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratory-gamete-bank': {
      id: '/laboratory-gamete-bank'
      path: '/laboratory-gamete-bank'
      fullPath: '/laboratory-gamete-bank'
      preLoaderRoute: typeof LaboratoryGameteBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fertility-cases': {
      id: '/fertility-cases'
      path: '/fertility-cases'
      fullPath: '/fertility-cases'
      preLoaderRoute: typeof FertilityCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donors': {
      id: '/donors'
      path: '/donors'
      fullPath: '/donors'
      preLoaderRoute: typeof DonorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consents': {
      id: '/consents'
      path: '/consents'
      fullPath: '/consents'
      preLoaderRoute: typeof ConsentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communications': {
      id: '/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof CommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients_/$patientId': {
      id: '/patients_/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fertility-cases_/$caseId': {
      id: '/fertility-cases_/$caseId'
      path: '/fertility-cases/$caseId'
      fullPath: '/fertility-cases/$caseId'
      preLoaderRoute: typeof FertilityCasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/lots/$lotId': {
      id: '/inventory/lots/$lotId'
      path: '/lots/$lotId'
      fullPath: '/inventory/lots/$lotId'
      preLoaderRoute: typeof InventoryLotsLotIdRouteImport
      parentRoute: typeof InventoryRoute
    }
  }
}

interface InventoryRouteChildren {
  InventoryLotsLotIdRoute: typeof InventoryLotsLotIdRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryLotsLotIdRoute: InventoryLotsLotIdRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  CommunicationsRoute: CommunicationsRoute,
  ConsentsRoute: ConsentsRoute,
  DonorsRoute: DonorsRoute,
  FertilityCasesRoute: FertilityCasesRoute,
  InventoryRoute: InventoryRouteWithChildren,
  LaboratoryGameteBankRoute: LaboratoryGameteBankRoute,
  MedicationPharmacyRoute: MedicationPharmacyRoute,
  PatientFollowupRoute: PatientFollowupRoute,
  PatientsRoute: PatientsRoute,
  ProceduresRoute: ProceduresRoute,
  SettingsRoute: SettingsRoute,
  SmartPrescriptionsRoute: SmartPrescriptionsRoute,
  TasksRoute: TasksRoute,
  TreatmentJourneysRoute: TreatmentJourneysRoute,
  FertilityCasesCaseIdRoute: FertilityCasesCaseIdRoute,
  PatientsPatientIdRoute: PatientsPatientIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
